from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import Paragraph, Table, TableStyle
from reportlab.lib.units import inch
from datetime import datetime

def generate_test_report():
    # Create PDF with better styling
    c = canvas.Canvas("test_report.pdf", pagesize=letter)
    width, height = letter

    # Add a light gray background header
    c.setFillColor(colors.lightgrey)
    c.rect(0, height - 120, width, 120, fill=True)
    
    # Header with logo placeholder
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 24)
    c.drawString(inch, height - 40, "SmartBites ")
    
    # Report title with current date
    current_date = datetime.now().strftime("%Y-%m-%d")
    c.setFont("Helvetica", 14)
    c.drawString(inch, height - 60, f"Daily Order Report - {current_date}")
    c.setFont("Helvetica", 12)
    c.drawString(inch, height - 80, "University Cafeteria")
    c.drawString(inch, height - 100, "Generated By: SmartBites Admin Panel")

    # Add decorative line
    c.setStrokeColor(colors.blue)
    c.setLineWidth(2)
    c.line(inch, height - 130, width - inch, height - 130)

    # Summary Section with box
    y = height - 180
    c.setFillColor(colors.blue)
    c.rect(inch, y, width - 2*inch, 80, fill=False)
    c.setFillColor(colors.black)
    
    c.setFont("Helvetica-Bold", 16)
    c.drawString(1.2*inch, y + 60, "Summary Section")
    c.setFont("Helvetica", 12)
    c.drawString(1.2*inch, y + 40, f"Total Orders Processed: 13")
    c.drawString(1.2*inch, y + 25, f"Total Revenue: Rs. 527.29")
    c.drawString(1.2*inch, y + 10, f"Active Users: 3")

    # Order Breakdown Section
    y = height - 300
    c.setFont("Helvetica-Bold", 16)
    c.drawString(inch, y, "Order Breakdown")
    
    # Create table headers
    data = [['Order ID', 'User ID', 'Items', 'Time', 'Amount (PKR)']]
    # Add sample data rows
    data.extend([
        ['1', 'U001', 'Burger x2', '10:30 AM', '250'],
        ['2', 'U002', 'Pizza x1', '11:45 AM', '277.29']
    ])

    table = Table(data, colWidths=[1*inch, 1*inch, 1.5*inch, 1.2*inch, 1.3*inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.blue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.white),
        ('TEXTCOLOR', (0, 1), (-1, -1), colors.black),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    table.wrapOn(c, width, height)
    table.drawOn(c, inch, y - 100)

    # Analytics Section
    y = height - 500
    c.setFont("Helvetica-Bold", 16)
    c.drawString(inch, y, "Analytics Insights")
    c.setFont("Helvetica", 12)
    c.drawString(inch, y - 25, "Peak Order Hours: 11:00 AM - 2:00 PM")
    c.drawString(inch, y - 45, "Most Popular Items: Burger, Pizza")
    c.drawString(inch, y - 65, "Payment Methods: Cash (60%), Card (40%)")

    # Footer
    c.setFont("Helvetica", 8)
    c.drawString(inch, inch, f"Report generated on {current_date}")
    c.drawString(width - 3*inch, inch, "Page 1 of 1")

    c.save()
    print("Report generated successfully as 'test_report.pdf'")

if __name__ == "__main__":
    generate_test_report()
